(load "SICP/ch02/2.2/2.17.scm")
(define (reverse items)
  (define items-length (length items))
  (define (reverse-items items items-number)
    (if (= items-number 0)
        (list (car items))
        (cons (list-ref items items-number) (reverse-items items (- items-number 1))))
    )
  (reverse-items items (- items-length 1))
  )